# Generated by Django 5.1.3 on 2024-11-21 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name": "Faculty", "verbose_name_plural": "Faculties"},
        ),
        migrations.AddField(
            model_name="faculty",
            name="students_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="faculty",
            name="teacher_to_student_ratio",
            field=models.PositiveIntegerField(
                default=35,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
